---
title: "Aphasia Rehabilitation Research Technology Mapping Project"
description: |
  The Aphasia Tech Map is a product of the [Collaboration of Aphasia Trialists](https://www.aphasiatrials.org) Working Group 4,  sponsored by the [Centre for Research Excellence in Aphasia Recovery and Rehabilitation](https://www.latrobe.edu.au/research/centres/health/aphasia).
site: distill::distill_website
---

```{css, echo = F}

d-appendix{
  display: none !important;
}

d-title h1 {
font-size: 1.35rem;
grid-column-gap: 62px;
}

/*Fix for Marker Clusters*/
.marker-cluster {
  background-color: #31882A20 !important;
}

.marker-cluster div {
  background-color: #31882A !important;
  color: #fff !important;
}

d-article{
  margin-top: 0px;
  max-height: 90vh !important;
  padding-top: 0px;
}

l-screen{
  margin: 1%;
}

```

```{r, include=FALSE}
library(here)
library(tidyverse)
library(leaflet)

# responses = read.csv(here("data", "aphasia-tech-responses.csv")) %>%
#   

google_data  = readRDS(here::here("google_data.rds"))
data = google_data %>%
  mutate(id = row_number()) %>%
  mutate(link=paste0("list_view.html#",id),
         Name = paste0("<a href=", link, ">", Title, "</a>")
         )

```

```{r, echo = F, layout = "l-screen-inset", out.height = "60vh"}
data %>%
  rename(lng = Lon, lat = Lat) %>%
  leaflet() %>%
  setView(lng = 20, lat = 30, zoom = 2) %>% 
  addTiles() %>%
  addMarkers(popup = ~Name,
             clusterOptions = markerClusterOptions(
                               maxClusterRadius = 30,
                               showCoverageOnHover = F)
             )
```

<center><small>
*Website built by [Rob Cavanaugh](https://rbcavanaugh.github.io) with assistance from [John Pierce](http://www.aphasiatherapyonline.com/aboutdetailed.html)*
<br>
*Last updated on `r Sys.Date()`*
</small></center>