---
title: "Current Aphasia Research Studies"
---

```{css, echo = F}
/* Don't display the title on the map page so there's more map*/
d-title, d-byline {
  display: none !important;
}

d-appendix{
  display: none !important;
}

/*Fix for Marker Clusters*/
.marker-cluster {
  background-color: #31882A20 !important;
}

.marker-cluster div {
  background-color: #31882A !important;
  color: #fff !important;
}

d-article{
  margin-top: 45px;
  max-height: 90vh !important;
  padding-top: 5px;
}

```

```{r, include=FALSE}
library(here)
library(tidyverse)
library(leaflet)

responses = read.csv(here("data", "aphasia-tech-responses.csv")) %>%
  mutate(id = row_number())

data = responses %>%
  mutate(link=paste0("list_view.html#",id),
         Name = paste0("<a href=", link, ">", Title, "</a>")
         )

```

```{r, echo = F, layout = "l-screen", out.height = "92vh"}
data %>%
  rename(lng = Lon, lat = Lat) %>%
  leaflet() %>%
  setView(lng = 30, lat = 40, zoom = 2) %>% 
  addTiles() %>%
  addMarkers(popup = ~Name,
             clusterOptions = markerClusterOptions(
                               maxClusterRadius = 30,
                               showCoverageOnHover = F)
             )
```

